version: "3.9"

services:
  minecraft:
    image: itzg/minecraft-server:latest
    container_name: ${SERVER_NAME}-minecraft-server
    restart: unless-stopped
    ports:
      - ":25565"
    volumes:
      - /home/server/MinecraftServer/${SERVER_NAME}/data:/data
    environment:
      EULA: "true"
      VERSION: ${SERVER_VERSION}
      MAX_RAM: ${SERVER_RAM}
      INIT_MEMORY: 1G
      CPU_COUNT: ${SERVER_CPU}